export const listTools = [
  {
    id: 1,
    gambar: "/assets/tools/js.png",
    nama: "JavaScript",
    ket: "Language",
    dad: "100",
  },
  {
    id: 2,
    gambar: "/assets/tools/php.png",
    nama: "PHP",
    ket: "Language",
    dad: "200",
  },
  {
    id: 3,
    gambar: "/assets/tools/reactjs.png",
    nama: "React JS",
    ket: "Frontend Framework",
    dad: "300",
  },
  {
    id: 4,
    gambar: "/assets/tools/nextjs.png",
    nama: "Next JS",
    ket: "Frontend Framework",
    dad: "400",
  },
  {
    id: 5,
    gambar: "/assets/tools/ts.png",
    nama: "TypeScript",
    ket: "Language",
    dad: "500",
  },
  {
    id: 6,
    gambar: "/assets/tools/tailwind.png",
    nama: "Tailwind CSS",
    ket: "CSS Framework",
    dad: "600",
  },
  {
    id: 7,
    gambar: "/assets/tools/html.png",
    nama: "HTML5",
    ket: "Markup Language",
    dad: "700",
  },
  {
    id: 8,
    gambar: "/assets/tools/css.png",
    nama: "CSS3",
    ket: "Styling",
    dad: "800",
  },
  {
    id: 9,
    gambar: "/assets/tools/nodejs.png",
    nama: "Node JS",
    ket: "Backend Runtime",
    dad: "900",
  },
  {
    id: 10,
    gambar: "/assets/tools/mysql.png",
    nama: "MySQL",
    ket: "Database",
    dad: "1000",
  },
  {
    id: 11,
    gambar: "/assets/tools/github.png",
    nama: "GitHub",
    ket: "Version Control",
    dad: "1100",
  },
  {
    id: 12,
    gambar: "/assets/tools/vscode.png",
    nama: "Visual Studio Code",
    ket: "Code Editor",
    dad: "1200",
  },
  {
    id: 13,
    gambar: "/assets/tools/figma.png",
    nama: "Figma",
    ket: "Design Tool",
    dad: "1300",
  },
  {
    id: 14,
    gambar: "/assets/tools/firebase.png",
    nama: "Firebase",
    ket: "Backend Service",
    dad: "1400",
  },
];

export const listProyek = [
  {
    id: 1,
    image: "/assets/proyek/art.png",
    title: "Art Palette Matcher",
    subtitle: "A tool that extracts dominant colors from uploaded images and generates matching palettes...",
    fullDescription: "A tool for artists and designers that extracts dominant colors from uploaded images and generates a matching or complementary color palette. Built with React, CSS3, and HTML5, it provides an intuitive interface for uploading images and instantly visualizing extracted color swatches — helping creatives build cohesive color schemes for their projects.",
    borderColor: "#3B82F6",
    gradient: "linear-gradient(145deg, #3B82F6, #000)",
    url: "https://github.com/Hassanezz11/palette-matcher",
    live: "https://Hassanezz11.github.io/palette-matcher",
    dad: "100",
  },
  {
    id: 2,
    image: "/assets/proyek/collab-whiteboard.png",
    title: "Collaboration Whiteboard",
    subtitle: "A real-time collaborative drawing and note board synced across users via WebSockets...",
    fullDescription: "A web-based drawing and note board where multiple users can draw, add sticky notes, move items, and collaborate in real time. Uses WebSockets (Socket.io) for syncing across users and implements drag-and-drop features. Built with React, Express, and Zustand for state management, it delivers a seamless multiplayer experience directly in the browser.",
    borderColor: "#10B981",
    gradient: "linear-gradient(180deg, #10B981, #000)",
    url: "https://github.com/Hassanezz11/collab-whiteboard",
    live: "https://hassanezz11.github.io/collab-whiteboard/",
    dad: "200",
  },
  {
    id: 3,
    image: "/assets/proyek/typing-game.png",
    title: "Typing Speed Challenge",
    subtitle: "A fast-paced browser game that tests typing speed and accuracy with real-time feedback...",
    fullDescription: "A fast-paced browser game that tests your typing speed and accuracy in a fun and interactive way. The player has 60 seconds to type as many randomly generated words as possible, with real-time feedback, score tracking, and a final performance summary. Features WPM calculation, live timer, visual cues for correct and incorrect typing, smooth UI transitions, and responsive layout. Runs entirely on the frontend with no backend dependency.",
    borderColor: "#3B82F6",
    gradient: "linear-gradient(145deg, #3B82F6, #000)",
    url: "https://github.com/Hassanezz11/typing-speed-game",
    live: "https://typingame-hassanezz.vercel.app/",
    dad: "300",
  },
  {
    id: 4,
    image: "/assets/proyek/soukwany.png",
    title: "Soukwany",
    subtitle: "A digital product store built for seamless online shopping of digital goods...",
    fullDescription: "Soukwany is a digital product website store designed to showcase and sell digital goods online. Built with a modern full-stack architecture, it features product listings, a clean storefront UI, and a smooth purchasing experience. The platform is optimized for performance and usability, making it easy for customers to browse and purchase digital products.",
    borderColor: "#10B981",
    gradient: "linear-gradient(180deg, #10B981, #000)",
    url: "https://github.com/Hassanezz11/digital-product",
    live: "https://soukwany.com",
    dad: "400",
  },
  {
    id: 5,
    image: "/assets/proyek/branch-predictor.png",
    title: "Branch Predictor",
    subtitle: "A simulation tool for visualizing and comparing CPU branch prediction algorithms...",
    fullDescription: "A simulation and visualization tool for CPU branch prediction algorithms. Branch predictors are a fundamental part of modern processor design — this project brings them to life by letting users input instruction sequences and compare how different prediction strategies (e.g., static, 1-bit, 2-bit saturating counter) perform. Great for computer architecture students and enthusiasts.",
    borderColor: "#3B82F6",
    gradient: "linear-gradient(145deg, #3B82F6, #000)",
    url: "https://github.com/Hassanezz11/prediction-path",
    live: "#",
    dad: "500",
  },
  {
    id: 6,
    image: "/assets/proyek/personal-portfolio.png",
    title: "Personal Portfolio",
    subtitle: "An interactive 3D portfolio showcasing skills, experience, and projects...",
    fullDescription: "An interactive web portfolio built with React, Vite, and Tailwind CSS. Features a physics-based 3D lanyard card using React Three Fiber and Rapier, scroll animations with AOS, a ChromaGrid project showcase, and a contact form. Deployed on Vercel and designed as a professional hub for employers and collaborators to explore skills and work.",
    borderColor: "#10B981",
    gradient: "linear-gradient(180deg, #10B981, #000)",
    url: "#",
    live: "https://ezzouhir-hassan.vercel.app",
    dad: "600",
  },
];
